### PR TITLE
[TEST COMMIT] Investigate merge bug

### PR DESCRIPTION
**Pull request by rexagod**
image
***
image
***
Logs: https://prow.ci.openshift.org/pr?query=is%3Apr+repo%3Ared-hat-storage%2Fmcg-ms-console+author%3Arexagod+head%3Amerge-bug
***
Similar issue: https://github.com/kubernetes/test-infra/issues/24141#issuecomment-1016624541

### CODE REVIEW

**Comment by rexagod** [comment]
Finally.
***
image

**Comment by furkatgofurov7** [comment]
> 

@rexagod hi, can you share, what was the solution for fixing the tide, we are seeing the same issues in our prow. Thanks!

**Pull request merged**
